name: healthpay_quote_sdk_example
description: Example app for the HealthPay Quote Flutter SDK.
publish_to: none
version: 0.1.0

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=3.10.0"

dependencies:
  flutter:
    sdk: flutter
  healthpay_quote_sdk:
    path: ../

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
